version: "3.5"
services:
  database:
    image: mysql:5.7.23
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  app:
    image: zephinzer/golang-dev:0.1.5
    user: "${UID}"
    entrypoint: ["start"]
    environment:
      DB_HOST: database
      DB_PORT: "3306"
      DB_DATABASE: database
      DB_USER: user
      DB_PASSWORD: password
      PORT: "54321"
    ports:
    - "54321:54321"
    volumes:
    - "./:/go/src/app:rw"
    - "./.cache/pkg:/go/pkg:rw"
    depends_on:
    - database
  migrator:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: build
    user: "${UID}"
    entrypoint: ["./app", "--migrate"]
    environment:
      DB_HOST: database
      DB_PORT: "3306"
      DB_DATABASE: database
      DB_USER: user
      DB_PASSWORD: password
    volumes:
    - "./:/go/src/app:rw"
    - "./.cache/pkg:/go/pkg:rw"
    depends_on:
    - database